### ISSUE TITLE
Mixed query: case DOI + first author last name

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/biblio-glutton#19]
The following query is rejected: 

http://localhost:8080/service/lookup?doi=10.3389%2Ffnhum.2011.00050&firstAuthor=Keller

We have a DOI and a first author last name. 

```json
{
  "code": "400",
  "message": "The supplied parameters were not sufficient to select the query"
}
```

Of course if we send a DOI only it works: 

http://localhost:8080/service/lookup?doi=10.3389%2Ffnhum.2011.00050

So this is not consistent (more arguments is always better): 
- we should accept the query with these parameters
- we perform a normal DOI lookup with the provided DOI
- by default "postValidate" is true, so we check if the provided author name soft matches the author name of the record, if it matches, return the result, otherwise the not found due to post-validation message / in the above example, post-validation fails, because the author for this DOI is not "Keller"
- if  "postValidate" is false, we ignore first author last name, and simply return the result

**Comment by kermitt2** [comment]
Actually this one works fine:

http://localhost:8080/service/lookup?doi=10.3389%2Ffnhum.2011.00050&firstAuthor=Furuya

So the problem is the response code and message, it should be 404
{
  "message": "Article found but it didn't passed the postValidation."
}

**Comment by lfoppiano** [comment]
it should be fixed. It now returns 404, as expected.

**Comment by kermitt2** [comment]
Super !
