### ISSUE TITLE
Some lookup should not fail if ES is not started

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/biblio-glutton#2]
For instance

>  curl http://localhost:8080/service/lookup?doi=10.1484/J.QUAESTIO.1.103624
{"code":"502","message":"Cannot fetch data from Elasticsearch. "}

elasticsearch is not used for DOI lookup, so the service should not fail. It's good support simple lookup usage too, without the advanced "matching" functions.

**Comment by lfoppiano** [comment]
This is a bug from my side :-(
