### ISSUE TITLE
Result from  best OA URL rather in json

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/biblio-glutton#28]
Currently results for `/service/oa?` is just the string of the OA URL. 

Finally I think it would be better to have a json answer, for example:

> curl "http://localhost:8080/service/oa?doi=10.1107/S0907444911008754"

```
{
   "oaLink": "http://journals.iucr.org/d/issues/2011/05/00/bw5391/bw5391.pdf"
}
```

It will be easier to integrate the result in the web extension, and it will make possible to easily add optionally more information in the response (for instance if someone want also the URL of the ISTEX full text, or if we want to integrate custom repo).

**Comment by lfoppiano** [comment]
Should be now implemented, I've quickly tested.

**Comment by kermitt2** [comment]
you're faster than Mr Robot :D it works, many thanks Luca !!
