### ISSUE TITLE
Add the ability to update lmdb data from crossref

### ISSUE THREAD

**Issue by seanrife** [kermitt2/biblio-glutton#38]
At present, updating the lmdb database recompiling the entire db from scratch. It would be nice if incremental updates could be made using the crossref metadata plus API and/or OAI-PMH service.

**Comment by karatekaneen** [comment]
Would love this feature and would be glad to help if I could, although Java isn't my forte maybe I can figure it out.

Where should I start to look for adding a "append" function of fresh data?

**Comment by kermitt2** [comment]
This is implemented with version `0.2`. I am running the service since several weeks and daily update with Crossref REST API is smooth and just takes a few minutes.
