### ISSUE TITLE
Add the ability to compile lmdb from crossref premium

### ISSUE THREAD

**Issue by seanrife** [kermitt2/biblio-glutton#39]
It would be nice if we could compile the lookup database using crossref metadata plus, which is in a different format the the greenelab metadata dump. Specifically, the data from crossref are split across multiple files, each with 10,002 lines.

Example files from crossref plus attached.

[examples.zip](https://github.com/kermitt2/biblio-glutton/files/3537298/examples.zip)

**Comment by kermitt2** [comment]
implemented in PR #61

**Comment by kermitt2** [comment]
This is implemented with version `0.2`. Metadata Plus snapshot is the best way to initialize biblio-glutton.
