### ISSUE TITLE
PMC ID look-up

### ISSUE THREAD

**Issue by kermitt2** [kermitt2/biblio-glutton#41]
Still some confusing aspects with the PMC ID identifier arguments: 

http://cloud.science-miner.com/glutton/service/lookup?pmc=1017419

returns record for `{ pmid : "1017419" }` 

For querying a PMC article with a PMC ID, we need the prefix PMC, e.g.
http://cloud.science-miner.com/glutton/service/lookup?pmc=PMC1017419
however, the lookup is failing (404), while it should normally because it's an old article: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1017419/

**Comment by kermitt2** [comment]
PMC1017419 apparently has no PMID (I thought every PMC item has a PMID!), so it is not in the PMID/PMC ID mapping and we can't find it. However the problem with returning `{ pmid : "1017419" }` record based on the PMC ID query is a wrong behaviour of biblio-glutton.

**Comment by lfoppiano** [comment]
I've pushed a fix, however I realise I don't have the data here, so I cannot test it :-( 

It was a small bug where the controller was pointing to the wrong method (retrieveByPmid, instead of retrieveByPmc)

**Comment by kermitt2** [comment]
I've tested the fix and it works fine, many thanks !
