### ISSUE TITLE
Slow importing of Crossref full metadata dump in LMDB

### ISSUE THREAD

**Issue by steppo83** [kermitt2/biblio-glutton#88]
Hello,
I'm trying to use biblio-glutton inside a pod in kubernetes but I'm facing a slowness the importing of  Crossref full metadata dump:
![image](https://user-images.githubusercontent.com/19529745/225638662-5c9e0a6a-592c-4694-9865-5160dc7ea3be.png)

Pos has this setup:
 resources:        
   limits:          
     cpu: '2'          
     memory: 8Gi        
  requests:          
     cpu: 250m          
     memory: 64Mi

![image](https://user-images.githubusercontent.com/19529745/225638982-088909ee-f9c9-457c-b236-796dc5ab2091.png)

The config of biblio-glutton has the default settings.
Is there that I'm missing? How to improve the importing?

Thanks!

**Comment by karatekaneen** [comment]
Sounds like a Kubernetes issue to me. We are running Glutton in K8s and haven't encountered indexing this slow. 
What kind of disks do you have backing the PV?

**Comment by karatekaneen** [comment]
I actually encountered slow indexing myself when running the version from #90 and the 2023 dump. Nothing in our environment has changed except those two things and we usually index about 5-7k/s. Now running on less than 1k/s:

```
crossrefLookup
             count = 62658487
         mean rate = 1013.66 events/second
     1-minute rate = 927.42 events/second
     5-minute rate = 836.58 events/second
    15-minute rate = 800.44 events/second
```

**Comment by lfoppiano** [comment]
As discussed in [this thread](https://github.com/kermitt2/biblio-glutton/pull/92#issuecomment-2096330755), the first suspect is the disk throughput, and the second is the RAM memory.
